ojo-network/ojo

- docs/design/README.md
- docs/design/TEMPLATE.md
Adds a design doc process & template
This is a part of #15
---
I have...
I have...
> docs: add design docs folder

- LICENSE
closes: #17
---
I have...
I have...
> chore: add apache license

- .mergify.yml
Adds mergify automerge 
---
I have...
I have...
> ci: add mergify auto merge

- app/params/app_settings.go
- cmd/ojod/main.go
- x/oracle/types/vote_test.go
moves init to address prefix, to support import files as dependencies
---
I have...
I have...
> feat: move init to address prefix

- util/reward/reward.go
- x/oracle/abci.go
- x/oracle/abci_test.go
closes: #64 
- ExchangeRate will not get calculated and set unless total power of the denom's ballot is over `VoteThreshold`
- Added enblocker test for testing `VoteThreshold` allowing/disallowing denom's exchange rate to get set
- Found edge case not getting handled by `CalculateRewardFactor`
---
I have...
I have...
> feat: Enforce voting threshold

- .github/workflows/simulations.yml
- .golangci.yml
- Makefile
- app/app.go
- tests/simulation/sim_test.go
- tests/simulation/state.go
Adds simulation tests
closes: #40
---
I have...
I have...
> ci: add simulation tests

- x/oracle/README.md
- x/oracle/simulations/operations.go
closes: #XXXX
---
I have...
I have...
> docs: small copypasta cleanup

- x/oracle/abci.go
- x/oracle/abci_test.go
- x/oracle/keeper/ballot.go
- x/oracle/keeper/params.go
- x/oracle/simulations/genesis.go
- x/oracle/types/ballot.go
- x/oracle/types/ballot_test.go
- x/oracle/types/params.go
- x/oracle/types/params_test.go
closes: #105 
Also updates oracle endblocker tests `TestEndBlockerVoteThreshold` and `TestEndBlockerValidatorRewards` to run with three validators.
---
I have...
I have...
> fix: Backport power threshold fixes

- Makefile
- tests/e2e/orchestrator/orchestrator.go
- tests/grpc/historical.go
- tests/grpc/price_listener.go
- Use MandatoryList instead of AcceptList for checking prices and medians in e2e tests
- Add TODO for updating e2e test output
- Update price-feeder-e2e docker image repo URL
- Add --skip-provider-check to price feeder docker runner in e2e tests
- Removed price-feeder docker commands in Makefile (will be auto pushed by price-feeder repo)
> fix: AcceptList requirement in e2e tests

- x/oracle/types/params.go
- x/oracle/types/params_test.go
closes: #150
---
I have...
I have...
> feat: Validate slash window is multiple of vote period

- app/modules.go
- app/params/app_settings.go
Updates the default gov voting period to 3 days, instead of the default 5.
---
I have...
I have...
> feat: update default gov voting period

- .golangci.yml
closes: #XXXX
---
I have...
I have...
> ci: remove depguard from golanglint

- CHANGELOG.md
- app/app.go
- app/upgrades.go
- x/oracle/keeper/migrations.go
closes: #XXXX
---
I have...
I have...
> fix: add migration to update ValidatorRewardSet to list

- CHANGELOG.md
- go.mod
- go.sum
Burberry patch for the Ojo Chain
---
I have...
I have...
> chore(deps): update cosmos sdk to v0.46.13

- .github/workflows/build.yml
- .github/workflows/code-ql.yml
- .github/workflows/debug.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/simulations.yml
- .github/workflows/tests.yml
Updating go version used in CI to 1.20 to sync wtih code
---
I have...
I have...
> ci: updated go version used in ci to 1.20

- app/encoding.go
- app/params/proto.go
closes: #XXXX
---
I have...
I have...
> fix: register auth types in MakeEncodingConfig

- app/app.go
Explicit client registration for ibc go v7 
reference : [here](https://github.com/cosmos/ibc-go/blob/v7.0.0/docs/ibc/integration.md#integrating-light-clients)
closes: #XXXX
---
I have...
I have...
> feat: 07-tendermint light client registration

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> chore: Add v0.2.1 upgrade handler

- app/upgrades.go
Adds an upgrade handler for the GMP module. This will be used for v0.3.0
---
I have...
I have...
> feat: v0.3.0 upgrade handler

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> chore: add v0.3.0-rc2 upgrade handler

- app/upgrades.go
Adds the v0.3.0-rc3 upgrade handler
---
I have...
I have...
> chore: add v0.3.0-rc3 upgrade handler

- x/gmp/client/cli/tx.go
- x/gmp/types/msgs.go
- x/gmp/types/msgs_test.go
…tract call into seperate cli commands
closes: #XXXX
---
I have...
I have...
> feat: Separate relaying price data and relaying price data with a contract call into separate cli commands

- x/gmp/keeper/keeper.go
closes: #XXXX
---
I have...
I have...
> fix: Use msg token amount as fee amount for gmp ibc transfer

- x/gmp/client/cli/tx.go
- x/gmp/types/msgs.go
closes: #XXXX
---
I have...
I have...
> fix: Pass empty address for customer contract address in relay tx

- app/app.go
- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> fix: Unblock gmp module account from bank keeper

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> chore: remove v0.3.0-rc upgrades

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> chore: v0.3.1-rc2 upgrade handler

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> fix: Set IBC client params in v0.4.0 upgrade handler

- .github/workflows/release.yml
> fix: Revert "chore(deps): bump goreleaser/goreleaser-action from 5 to 6"

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> fix: Add gov proposal migration in v0.3.1 upgrade handler

- app/upgrades.go
closes: #XXXX
---
I have...
I have...
> fix: Update v0.4.1 upgrade handler for agamotto upgrade

- app/gmpmiddleware/handler.go
- x/gmp/keeper/keeper.go
- x/gmp/keeper/msg_server.go
Uses the GMP messages coming from axelar to create new payments on the GMP module.
> feat: gmp handling create payment

- x/gmp/types/payment.go
closes: #XXXX
---
I have...
I have...
> fix: handle no previous payment updates
